/**
 * Test agent0-ts SDK ArweaveClient Integration
 *
 * Tests the SDK's ArweaveClient wrapper around Turbo SDK:
 * 1. SDK initialization with arweave: true
 * 2. ArweaveClient.addRegistrationFile() with tags
 * 3. ArweaveClient.getFile() from multiple gateways
 * 4. Tag generation via arweave-tags utility
 */

import 'dotenv/config';
import { SDK } from 'agent0-sdk';

async function main() {
  console.log('🧪 Testing agent0-ts SDK ArweaveClient Integration\n');
  console.log('═'.repeat(80));

  // Test 1: Initialize SDK with Arweave enabled
  console.log('\n📝 Test 1: Initialize SDK with Arweave Support');
  console.log('-'.repeat(80));

  const config = {
    chainId: 11155111 as const, // Sepolia
    rpcUrl: process.env.RPC_URL!,
    signer: process.env.PRIVATE_KEY!,
    arweave: true, // Enable Arweave with ArweaveClient
    // Note: No subgraph for this test - testing Arweave only
  };

  console.log('✓ Configuration loaded');
  console.log(`  Chain: Sepolia (${config.chainId})`);
  console.log(`  Arweave: Enabled`);

  const sdk = new SDK(config);
  console.log('✓ SDK initialized');

  // Verify ArweaveClient was created
  // @ts-ignore - accessing private property for testing
  if (sdk.arweaveClient) {
    console.log('✓ ArweaveClient created and available');
  } else {
    throw new Error('ArweaveClient not initialized!');
  }

  // Test 2: Create test agent data
  console.log('\n📝 Test 2: Create Test Agent Data');
  console.log('-'.repeat(80));

  const agent = sdk.createAgent(
    `SDK Test Agent ${Math.floor(Math.random() * 9000 + 1000)}`,
    'Testing agent0-ts SDK ArweaveClient integration',
    `https://example.com/agent-${Date.now()}.png`
  );

  console.log(`✓ Agent created: "${agent.name}"`);

  // Add capabilities
  await agent.setMCP(
    `https://mcp.example.com/${Date.now()}`,
    '2025-06-18',
    false // Disable crawling
  );
  console.log('✓ MCP endpoint added');

  await agent.setA2A(
    `https://a2a.example.com/${Date.now()}.json`,
    '0.35',
    false
  );
  console.log('✓ A2A endpoint added');

  agent.setAgentWallet('0x' + 'a'.repeat(40), 1);
  console.log('✓ Wallet configured');

  agent.setActive(true);
  console.log('✓ Agent set to active');

  // Test 3: Upload to Arweave via ArweaveClient
  console.log('\n📝 Test 3: Upload via SDK ArweaveClient');
  console.log('-'.repeat(80));

  const registrationData = agent.getRegistrationFile();
  console.log('✓ Registration file prepared:');
  console.log(`  Name: ${registrationData.name}`);
  console.log(`  Type: ${registrationData.type}`);
  console.log(`  Endpoints: ${registrationData.endpoints.length}`);
  console.log(`  Active: ${registrationData.active}`);

  const dataString = JSON.stringify(registrationData, null, 2);
  console.log(`  Size: ${dataString.length} bytes`);

  console.log('\n⏳ Uploading via ArweaveClient.addRegistrationFile()...');
  console.log('   This will generate comprehensive tags automatically');

  const startTime = Date.now();

  // @ts-ignore - accessing private method for testing
  const arUri = await sdk.arweaveClient.addRegistrationFile(
    registrationData,
    config.chainId
  );

  const duration = ((Date.now() - startTime) / 1000).toFixed(2);

  console.log(`\n✅ Upload successful in ${duration}s!`);
  console.log(`  Arweave URI: ${arUri}`);

  const txId = arUri.replace('ar://', '');
  console.log(`  Transaction ID: ${txId}`);

  // Test 4: Verify tags were generated
  console.log('\n📝 Test 4: Verify Automatic Tag Generation');
  console.log('-'.repeat(80));
  console.log('⏳ Waiting 5 seconds for indexing...');

  await new Promise(resolve => setTimeout(resolve, 5000));

  const query = `
    query {
      transaction(id: "${txId}") {
        tags {
          name
          value
        }
      }
    }
  `;

  const response = await fetch('https://arweave.net/graphql', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ query }),
  });

  const graphqlResult = await response.json();
  const retrievedTags = graphqlResult.data?.transaction?.tags || [];

  if (retrievedTags.length > 0) {
    console.log('✅ Tags automatically generated by SDK:\n');
    console.log('  Tag Name              | Value');
    console.log('  ' + '-'.repeat(70));

    for (const tag of retrievedTags) {
      const name = tag.name.padEnd(20);
      const value = tag.value.length > 50 ? tag.value.substring(0, 47) + '...' : tag.value;
      console.log(`  ${name} | ${value}`);
    }

    console.log(`\n✅ Total tags: ${retrievedTags.length}`);

    // Verify expected tags
    const expectedTags = [
      'Content-Type',
      'App-Name',
      'Protocol',
      'Data-Type',
      'Chain-Id',
      'Timestamp',
      'Has-MCP',
      'Has-A2A',
      'Has-Wallet',
      'Active'
    ];

    console.log('\n✅ Tag Presence Verification:');
    expectedTags.forEach(tagName => {
      const tag = retrievedTags.find((t: any) => t.name === tagName);
      if (tag) {
        console.log(`   ✓ ${tagName}: ${tag.value}`);
      } else {
        console.log(`   ✗ ${tagName}: MISSING`);
      }
    });
  } else {
    console.log('⏳ Tags not yet indexed (try again in 30-60 seconds)');
  }

  // Test 5: Test ArweaveClient.getRegistrationFile() - Parallel gateway retrieval
  console.log('\n📝 Test 5: Test SDK ArweaveClient.getRegistrationFile()');
  console.log('-'.repeat(80));
  console.log('⏳ Testing parallel gateway retrieval...');

  const getFileStart = Date.now();

  // @ts-ignore - accessing private method for testing
  const retrievedData = await sdk.arweaveClient.getRegistrationFile(arUri);

  const getFileDuration = ((Date.now() - getFileStart) / 1000).toFixed(2);

  console.log(`\n✅ Data retrieved in ${getFileDuration}s via parallel gateways!`);
  console.log('  Retrieved data:');
  console.log(`    Name: ${retrievedData.name}`);
  console.log(`    Type: ${retrievedData.type}`);
  console.log(`    Endpoints: ${retrievedData.endpoints.length}`);
  console.log(`    Active: ${retrievedData.active}`);

  // Verify data integrity
  if (retrievedData.name === registrationData.name) {
    console.log('  ✓ Data integrity verified!');
  } else {
    console.log('  ✗ Data integrity check failed!');
  }

  // Test Summary
  console.log('\n' + '═'.repeat(80));
  console.log('🎉 SDK ARWEAVECLIENT INTEGRATION TEST COMPLETE!\n');
  console.log('Summary of Tests:');
  console.log('  ✓ Test 1: SDK initialization with arweave: true');
  console.log('  ✓ Test 2: Agent creation with capabilities');
  console.log('  ✓ Test 3: Upload via ArweaveClient.addRegistrationFile()');
  console.log('  ✓ Test 4: Automatic tag generation verification');
  console.log('  ✓ Test 5: Parallel gateway retrieval via getFile()');
  console.log('\nagent0-ts SDK ArweaveClient: ✅ FULLY WORKING');
  console.log(`Transaction ID: ${txId}`);
  console.log(`View on Arweave: https://viewblock.io/arweave/tx/${txId}`);
  console.log('═'.repeat(80));
}

main().catch(console.error);
